DROP TABLE IF EXISTS PRODUCTS;  
CREATE TABLE PRODUCTS (  
ID INT AUTO_INCREMENT  PRIMARY KEY,  
PREODUCT_CODE VARCHAR(10) NOT NULL,  
PREODUCT_NAME VARCHAR(100) NOT NULL,
PREODUCT_DESC VARCHAR(200) NOT NULL,
PRICE INT(8) NOT NULL
);  